### ISSUE TITLE
No playback of live channels with VDR

### ISSUE THREAD

**Issue by monochromec** [pipelka/xbmc-addon-xvdr#142]
XMBC: Helix stable
VDR: 2.1.6-8yavdr0~trusty

Cannot turn on playback from live channels. I tried both VDR plugins (from the yavdr repo and a compiled version of a cloned GIT snapshot).

kodi.log: 

14:35:02 T:140471368996608  DEBUG: PVRManager - OpenLiveStream - opening live stream on channel 'Das Erste'
14:35:02 T:140471368996608   DEBUG: opening live stream for channel 'Das Erste'
14:35:02 T:140471368996608  NOTICE: AddOnLog: VDR XVDR Client: doing simple server-side timeshift
14:35:02 T:140471368996608   DEBUG: AddOnLog: VDR XVDR Client: Possible leak caused by workaround in GetLanguageCode
14:35:02 T:140471368996608    INFO: AddOnLog: VDR XVDR Client: Logged in at '1420810502+3600' to 'VDR-XVDR Server' Version: '0.9.9' with protocol version '5'
14:35:02 T:140471368996608    INFO: AddOnLog: VDR XVDR Client: Preferred Audio Language: eng
14:35:02 T:140471368996608   DEBUG: AddOnLog: VDR XVDR Client: changing to channel 369931212 (priority 50)
14:35:02 T:140471368996608    INFO: AddOnLog: VDR XVDR Client: sucessfully switched channel
14:35:02 T:140471368996608   DEBUG: CPVRChannelGroup - Persist - persisting channel group 'All channels' with 463 channels
14:35:02 T:140471368996608   DEBUG: PVRFile - Open - playback has started on filename pvr://channels/tv/All channels/0.pvr
14:35:02 T:140471368996608   DEBUG: CDVDInputStreamPVRManager::Open - stream opened: pvr://channels/tv/All channels/0.pvr
14:35:02 T:140471368996608  NOTICE: Creating Demuxer
14:35:02 T:140471368996608   ERROR: Get - failed to get stream
14:35:02 T:140471368996608   DEBUG: CDVDPlayer::SetCaching - caching state 2
14:35:02 T:140471368996608 WARNING: CDVDMessageQueue(audio)::Put MSGQ_NOT_INITIALIZED
14:35:02 T:140471368996608 WARNING: CDVDMessageQueue(video)::Put MSGQ_NOT_INITIALIZED
14:35:02 T:140471368996608   DEBUG: OnPlayBackStarted: play state was 1, starting 1
14:35:02 T:140471782098880   DEBUG: PlayFile: OpenFile succeed, play state 2
14:35:02 T:140471782098880   DEBUG: OnPlayBackStarted: play state was 2, starting 0
14:35:02 T:140471368996608   ERROR: ReadPacket - Error demux packet doesn't belong to a valid stream
14:35:02 T:140471782098880   ERROR: Previous line repeats 9 times.

**Comment by pipelka** [comment]
The vdr log would be more useful to see whats going on. Please use the latest git version of the vdr plugin.

**Comment by monochromec** [comment]
Here you go:

Jan  9 14:35:02 htpc vdr: [25961] XVDR: Welcome client 'XBMC Mediacenter' with protocol version '5'
Jan  9 14:35:02 htpc vdr: [25961] XVDR: Preferred language: eng,dos / type: 1
Jan  9 14:35:02 htpc vdr: [25961] XVDR: --------------------------------------
Jan  9 14:35:02 htpc vdr: [25961] XVDR: Started streaming of channel Das Erste (timeout 10 seconds, priority 50)
Jan  9 14:35:02 htpc vdr: [25964] cLiveStreamer stream processor thread started (pid=22057, tid=25964, prio=high)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: streamer thread started.
Jan  9 14:35:02 htpc vdr: [25963] XVDR: LiveQueue started
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Found available device 1
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Channel information found in cache
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Creating demuxers
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: MPEG2VIDEO PID: 101 720x576 DAR: 1.78 FPS: 25.000 (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: MPEG2AUDIO PID: 102 48000 Hz, 2 channels, Lang: deu (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: MPEG2AUDIO PID: 103 48000 Hz, 2 channels, Lang: mis (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: TELETEXT PID: 104 TXT (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: DVBSUB PID: 105 Lang: deu (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: AC3 PID: 106 48000 Hz, 2 channels, Lang: deu (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Successfully switched to channel 1 - Das Erste
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Starting PAT scanner
Jan  9 14:35:02 htpc vdr: [25964] XVDR: done switching.
Jan  9 14:35:02 htpc vdr: [25964] XVDR: streaming of channel started
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stored channel information in cache:
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: MPEG2VIDEO PID: 101 720x576 DAR: 1.78 FPS: 25.000 (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: MPEG2AUDIO PID: 102 48000 Hz, 2 channels, Lang: deu (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: MPEG2AUDIO PID: 103 48000 Hz, 2 channels, Lang: mis (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: TELETEXT PID: 104 TXT (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: DVBSUB PID: 105 Lang: deu (parsed: yes)
Jan  9 14:35:02 htpc vdr: [25964] XVDR: Stream: AC3 PID: 106 48000 Hz, 2 channels, Lang: deu (parsed: yes)

That error occurred with the latest version from git.

Please let me know if you need more information.

**Comment by pipelka** [comment]
Hmm. I don't know whats going on.

Please try the following:
* stop vdr
* remove /var/cache/vdr/plugins/xvdr/channelcache.dat
* start vdr
* try to playback channel

Please post the resulting vdr log.

**Comment by monochromec** [comment]
Here you go:

Jan 11 09:28:10 htpc vdr: [5414] XVDR: Welcome client 'XVDR Client' with protocol version '5'
Jan 11 09:28:10 htpc vdr: [5414] XVDR: Preferred language: eng,dos / type: 1
Jan 11 09:28:10 htpc vdr: [5414] XVDR: Channellist filter:
Jan 11 09:28:10 htpc vdr: [5414] XVDR: Free To Air channels: Yes
Jan 11 09:28:10 htpc vdr: [5414] XVDR: Only native language: No
Jan 11 09:28:10 htpc vdr: [5414] XVDR: Enabled CaIDs: 
Jan 11 09:28:10 htpc vdr: [5414] XVDR: FFFF
Jan 11 09:28:10 htpc vdr: [5414] XVDR: Setting channel update method: 3
Jan 11 09:28:21 htpc vdr: [5091] XVDR: Checking for channel updates ...
Jan 11 09:28:21 htpc vdr: [5091] XVDR: Client 0: 671 channels, no change
Jan 11 09:28:21 htpc vdr: [5091] XVDR: Done.
Jan 11 09:28:40 htpc vdr: [5091] loading /var/lib/vdr/plugins/xvdr/allowed_hosts.conf
Jan 11 09:28:40 htpc vdr: [5091] XVDR: Client 127.0.0.1:24710 with ID 1 connected.
Jan 11 09:28:40 htpc vdr: [5091] XVDR: Connected to wirbelscan plugin ...
Jan 11 09:28:40 htpc vdr: [5091] XVDR: wirbelscan plugin version: 0.0.7
Jan 11 09:28:40 htpc vdr: [5678] XVDR: Welcome client 'XBMC Mediacenter' with protocol version '5'
Jan 11 09:28:40 htpc vdr: [5678] XVDR: Preferred language: eng,dos / type: 1
Jan 11 09:28:40 htpc vdr: [5678] XVDR: --------------------------------------
Jan 11 09:28:40 htpc vdr: [5678] XVDR: Started streaming of channel Das Erste (timeout 10 seconds, priority 50)
Jan 11 09:28:40 htpc vdr: [5681] cLiveStreamer stream processor thread started (pid=5064, tid=5681, prio=high)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: streamer thread started.
Jan 11 09:28:40 htpc vdr: [5680] XVDR: LiveQueue started
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Found available device 1
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Channel information found in cache
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Creating demuxers
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: MPEG2VIDEO PID: 101 720x576 DAR: 1.78 FPS: 25.000 (parsed: yes)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: MPEG2AUDIO PID: 102 48000 Hz, 2 channels, Lang: deu (parsed: yes)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: MPEG2AUDIO PID: 103 48000 Hz, 2 channels, Lang: mis (parsed: yes)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: TELETEXT PID: 104 TXT (parsed: yes)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: DVBSUB PID: 105 Lang: deu (parsed: yes)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: AC3 PID: 106 48000 Hz, 2 channels, Lang: deu (parsed: yes)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Successfully switched to channel 1 - Das Erste
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Starting PAT scanner
Jan 11 09:28:40 htpc vdr: [5681] XVDR: done switching.
Jan 11 09:28:40 htpc vdr: [5681] XVDR: streaming of channel started
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stored channel information in cache:
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: MPEG2VIDEO PID: 101 720x576 DAR: 1.78 FPS: 25.000 (parsed: yes)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: MPEG2AUDIO PID: 102 48000 Hz, 2 channels, Lang: deu (parsed: yes)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: MPEG2AUDIO PID: 103 48000 Hz, 2 channels, Lang: mis (parsed: yes)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: DVBSUB PID: 105 Lang: deu (parsed: yes)
Jan 11 09:28:40 htpc vdr: [5681] XVDR: Stream: AC3 PID: 106 48000 Hz, 2 channels, Lang: deu (parsed: yes)

What is interesting though is that some channels sometimes work. Here's the part of the log after successfully connecting to such a channel:

Jan 11 09:31:58 htpc vdr: [5678] XVDR: Started streaming of channel MDR Sachsen (timeout 10 seconds, priority 50)
Jan 11 09:31:58 htpc vdr: [8019] cLiveStreamer stream processor thread started (pid=5064, tid=8019, prio=high)
Jan 11 09:31:58 htpc vdr: [8019] XVDR: streamer thread started.
Jan 11 09:31:58 htpc vdr: [8018] XVDR: LiveQueue started
Jan 11 09:31:58 htpc vdr: [8019] XVDR: Found available device 1
Jan 11 09:31:58 htpc vdr: [8019] XVDR: adding channel to cache
Jan 11 09:31:58 htpc vdr: [8019] XVDR: Creating demuxers
Jan 11 09:31:58 htpc vdr: [8019] XVDR: Stream: MPEG2VIDEO PID: 2901 0x0 DAR: 0.00 FPS: 0.000 (parsed: no)
Jan 11 09:31:58 htpc vdr: [8019] XVDR: Stream: MPEG2AUDIO PID: 2902 0 Hz, 0 channels, Lang: deu (parsed: no)
Jan 11 09:31:58 htpc vdr: [8019] XVDR: Stream: MPEG2AUDIO PID: 2903 0 Hz, 0 channels, Lang: mis (parsed: no)
Jan 11 09:31:58 htpc vdr: [8019] XVDR: Stream: TELETEXT PID: 2904 TXT (parsed: yes)
Jan 11 09:31:58 htpc vdr: [8019] XVDR: Successfully switched to channel 82 - MDR Sachsen
Jan 11 09:31:58 htpc vdr: [5095] TS buffer on device 1 thread ended (pid=5064, tid=5095)
Jan 11 09:31:58 htpc vdr: [5094] buffer stats: 112048 (2%) used
Jan 11 09:31:58 htpc vdr: [5094] receiver on device 1 thread ended (pid=5064, tid=5094)
Jan 11 09:31:58 htpc vdr: [8019] XVDR: Starting PAT scanner
Jan 11 09:31:58 htpc vdr: [8019] XVDR: done switching.
Jan 11 09:31:58 htpc vdr: [8020] receiver on device 1 thread started (pid=5064, tid=8020, prio=high)
Jan 11 09:31:58 htpc vdr: [8021] TS buffer on device 1 thread started (pid=5064, tid=8021, prio=high)
Jan 11 09:31:59 htpc vdr: [8019] XVDR: --------------------------------------
Jan 11 09:31:59 htpc vdr: [8019] XVDR: NEW AUDIO INFORMATION:
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Channels: 2
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Samplerate: 48000 Hz
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Bitrate: 192000 bps
Jan 11 09:31:59 htpc vdr: [8019] XVDR: --------------------------------------
Jan 11 09:31:59 htpc vdr: [8019] XVDR: --------------------------------------
Jan 11 09:31:59 htpc vdr: [8019] XVDR: NEW AUDIO INFORMATION:
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Channels: 2
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Samplerate: 48000 Hz
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Bitrate: 192000 bps
Jan 11 09:31:59 htpc vdr: [8019] XVDR: --------------------------------------
Jan 11 09:31:59 htpc vdr: [8019] XVDR: --------------------------------------
Jan 11 09:31:59 htpc vdr: [8019] XVDR: NEW PICTURE INFORMATION:
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Picture Width: 720
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Picture Height: 576
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Display Aspect Ratio: 1.78
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Frames per second: 25.00
Jan 11 09:31:59 htpc vdr: [8019] XVDR: --------------------------------------
Jan 11 09:31:59 htpc vdr: [8019] XVDR: streaming of channel started
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Stream: MPEG2VIDEO PID: 2901 720x576 DAR: 1.78 FPS: 25.000 (parsed: yes)
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Stream: MPEG2AUDIO PID: 2902 48000 Hz, 2 channels, Lang: deu (parsed: yes)
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Stream: MPEG2AUDIO PID: 2903 48000 Hz, 2 channels, Lang: mis (parsed: yes)
Jan 11 09:31:59 htpc vdr: [8019] XVDR: Stream: TELETEXT PID: 2904 TXT (parsed: yes)
Jan 11 09:32:18 htpc vdr: [8019] XVDR: streamer thread ended.
Jan 11 09:32:18 htpc vdr: [8019] cLiveStreamer stream processor thread ended (pid=5064, tid=8019)
Jan 11 09:32:18 htpc vdr: [8018] XVDR: LiveQueue stopped
Jan 11 09:32:18 htpc vdr: [5678] buffer stats: 110168 (1%) used
Jan 11 09:32:18 htpc vdr: [8021] TS buffer on device 1 thread ended (pid=5064, tid=8021)
Jan 11 09:32:18 htpc vdr: [5091] XVDR: Client with ID 1 seems to be disconnected, removing from client list
Jan 11 09:32:18 htpc vdr: [8020] buffer stats: 109792 (2%) used
Jan 11 09:32:18 htpc vdr: [8020] receiver on device 1 thread ended (pid=5064, tid=8020)
Jan 11 09:32:21 htpc vdr: [5064] switching to channel 1
Jan 11 09:32:21 htpc vdr: [8257] receiver on device 1 thread started (pid=5064, tid=8257, prio=high)
Jan 11 09:32:21 htpc vdr: [8258] TS buffer on device 1 thread started (pid=5064, tid=8258, prio=high)
Jan 11 09:32:22 htpc vdr: [8257] [xine..put] Detected video size 720x576

But even then the channel playback suffers performance / buffering issues as the played back stream has visible MPEG artifacts and the sound stutters as well every now and then. Machine spec. is a dual core Athlon II x2 245e running at 5800 bogomips. CPU utilization according to top is around 75% idle on both cores during playback.

Let me know if you need more information.

**Comment by monochromec** [comment]
Just took 13.2 for a spin to see if it makes any difference in comparison to 14. With 13.2, more channels play back correctly (fewer artifacts) and the channel list is retrieved instantly upon XBMC startup. In contrast, it takes about 30 seconds on my hardware to do the same with 14. Memory and CPU utilisation between the two versions is roughly the same.
