### ISSUE TITLE
kodi api change for series recordings

### ISSUE THREAD

**Issue by lostwithouthope** [pipelka/xbmc-addon-xvdr#143]
hi @pipelka 

this is no issue (yet).
i don't no if you have already seen it, but atm there is a discussion in the kodi repo.
see https://github.com/xbmc/xbmc/pull/5208
and http://forum.kodi.tv/showthread.php?tid=214469

as you are also a pvr addon developer I think you should join the discussions.

Thanks for your efforts I really like to use XVDR!

regards

**Comment by pipelka** [comment]
Thanks for the Information. But I'm not joining any kodi discussions (for historic reasons). These guys always know best what to do,... 

Anyways, I will implement whatever the outcome will be ;-)
