### ISSUE TITLE
server error in kodi 14 with vdr 2.2

### ISSUE THREAD

**Issue by fleixi** [pipelka/xbmc-addon-xvdr#148]
I have updated vdr (now 2.2), xvdr-server(now 0.9.9) and xvdr-addon( now 0.9.8) to the current master and now im not able to connect kodi with vdr anymore.

vdr is starting correctly and kodi and the addon starting also. But if i enable livetv the window with fetching channels is closing very fast and in the kodi.log is this error:
_________________________________
AddOnLog: VDR XVDR Client: Can't get response packet for Message ID: 63
PVR - GetChannels - addon 'VDR-XVDR Server:127.0.0.1' returned an error: server error
PVR - GetChannels - cannot get channels from client '1': server error
PVRChannelGroup - Load - failed to update channels
PVRChannelGroupInternal - Load - failed to load channels
PVR - Load - failed to load channels
PVRManager - Process - failed to load PVR data, retrying
________________________________________

saddly not very helpful.

**Comment by pipelka** [comment]
Please also post the vdr log.

**Comment by fleixi** [comment]
i have recompiled it 3 times and now it is working again. im sorry to bother without reasen.
